CREATE TABLE exchange (
  id int8 NOT NULL,
  name VARCHAR(255) NOT NULL,
  code SMALLINT NOT NULL,
  PRIMARY KEY (id)
)
WITH (OIDS=FALSE);

CREATE SEQUENCE IF NOT EXISTS seq_exchange;
ALTER SEQUENCE seq_exchange INCREMENT BY 50;
